services:
  ark-server:
    # https://ark.fandom.com/wiki/Server_configuration
    command:
      - "${ARK_MAP}?Port=7778?QueryPort=27015?SessionName=${ARK_SESSION_NAME}?MaxPlayers=${ARK_MAX_PLAYERS}?listen?ServerPassword=${ARK_SERVER_PASSWORD_JOIN}?AdminPassword=${ARK_SERVER_PASSWORD_ADMIN}"
      - "-nosteamclient"
      - "-game"
      - "-server"
      - "-NoBattlEye"
      - "-log"
    container_name: ark-server
    depends_on:
      ark-server-dl:
        condition: service_completed_successfully
    entrypoint: /data/ShooterGame/Binaries/Linux/ShooterGameServer
    hostname: ark-server
    image: steamcmd/steamcmd:ubuntu
    ports:
      - 7778:7778/udp
      - 7778:7778/tcp
      - 27015:27015/udp
      - 27015:27015/tcp
    restart: unless-stopped
    volumes:
      - ark-data:/data:z
      - ark-logs:/var/log/steamcmd:z
  ark-server-dl:
    command:
      - "+force_install_dir"
      - "/data"
      - "+login"
      - "anonymous"
      - "+app_update"
      - "376030"
      - "+quit"
    container_name: ark-server-dl
    hostname: ark-server-dl
    image: steamcmd/steamcmd:ubuntu
    restart: "no"
    volumes:
      - ark-data:/data:z
      - ark-logs:/var/log/steamcmd:z
volumes:
  ark-data:
    name: ark-data
  ark-logs:
    name: ark-logs
